name: Update EPG
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

     - name: Download EPG Data
        run: |
          # Switching to the Japan Terebi active mirror (High Uptime)
          curl -L "https://animenosekai.github.io/japanterebi-xmltv/guide.xml" -o guide.xml

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add guide.xml
          # This line ensures it never exits with error 1
          git commit -m "Update EPG" || echo "No changes"
          git push || echo "No push needed"
