name: Update EPG
on:
  schedule:
    - cron: '0 15 * * *' # Runs daily
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch EPG
        run: bash update.sh
      - name: Commit and Push
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add guide.xml
          git commit -m "Update EPG Data" || exit 0
          git push
