name: Update EPG
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download EPG Data
        run: |
          # Downloading directly to the runner
          curl -L "https://raw.githubusercontent.com/sh0m0/jp-epg/master/e.xml" -o guide.xml

      - name: Check File Size
        run: |
          ls -lh guide.xml
          # Ensure we didn't get a tiny error file
          if [ $(stat -c%s "guide.xml") -lt 10000 ]; then
            echo "File is too small, download likely failed."
            exit 1
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add guide.xml
          git commit -m "Update EPG Data" || echo "No changes to commit"
          git push
